import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  metadataBase: new URL("http://localhost:3000"),

  title: {
    default: "HomePilot",
    template: "%s | HomePilot",
  },
  description: "Smart Home Automation System",
  applicationName: "HomePilot",
  manifest: "/manifest.webmanifest",
  keywords: ["HomePilot", "Smart Home", "Automation", "IoT", "ESP32"],
  authors: [
    {
      name: "Dimas Abdul Yasir",
    },
  ],
  creator: "Dimas Abdul Yasir",
  publisher: "Dimas Abdul Yasir",
  // themeColor: "#2563eb",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "HomePilot",
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    title: "HomePilot",
    description: "Smart Home Automation System",
    siteName: "HomePilot",
    locale: "id_ID",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "HomePilot",
    description: "Smart Home Automation System",
  },
  robots: {
    index: true,
    follow: true,
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ServiceWorkerRegister />
        {children}
      </body>
    </html>
  );
}
